import type { FileItem } from "./types"

export const mockFiles: FileItem[] = [
  // Root folders
  {
    id: "folder-1",
    name: "Projects",
    type: "folder",
    size: 0,
    modifiedAt: new Date("2024-03-15"),
    createdAt: new Date("2024-01-10"),
    owner: "me",
    parentId: null,
    path: [],
    isFavorite: true,
    isDeleted: false,
  },
  {
    id: "folder-2",
    name: "Documents",
    type: "folder",
    size: 0,
    modifiedAt: new Date("2024-03-20"),
    createdAt: new Date("2024-02-01"),
    owner: "me",
    parentId: null,
    path: [],
    isFavorite: false,
    isDeleted: false,
  },
  {
    id: "folder-3",
    name: "Images",
    type: "folder",
    size: 0,
    modifiedAt: new Date("2024-03-18"),
    createdAt: new Date("2024-01-15"),
    owner: "me",
    parentId: null,
    path: [],
    isFavorite: true,
    isDeleted: false,
  },
  {
    id: "folder-4",
    name: "Shared with me",
    type: "folder",
    size: 0,
    modifiedAt: new Date("2024-03-10"),
    createdAt: new Date("2024-01-05"),
    owner: "Team",
    parentId: null,
    path: [],
    isFavorite: false,
    isDeleted: false,
  },
  // Files in root
  {
    id: "file-1",
    name: "Q1 Report.pdf",
    type: "pdf",
    size: 2500000,
    modifiedAt: new Date("2024-03-22"),
    createdAt: new Date("2024-03-22"),
    owner: "me",
    parentId: null,
    path: [],
    isFavorite: false,
    isDeleted: false,
  },
  {
    id: "file-2",
    name: "Presentation.pdf",
    type: "pdf",
    size: 5200000,
    modifiedAt: new Date("2024-03-21"),
    createdAt: new Date("2024-03-15"),
    owner: "me",
    parentId: null,
    path: [],
    isFavorite: true,
    isDeleted: false,
  },
  {
    id: "file-3",
    name: "Budget 2024.spreadsheet",
    type: "spreadsheet",
    size: 150000,
    modifiedAt: new Date("2024-03-19"),
    createdAt: new Date("2024-01-02"),
    owner: "me",
    parentId: null,
    path: [],
    isFavorite: false,
    isDeleted: false,
  },
  // Files inside Projects folder
  {
    id: "file-4",
    name: "Website Mockup.image",
    type: "image",
    size: 3500000,
    modifiedAt: new Date("2024-03-17"),
    createdAt: new Date("2024-03-17"),
    owner: "me",
    parentId: "folder-1",
    path: ["Projects"],
    isFavorite: false,
    isDeleted: false,
  },
  {
    id: "file-5",
    name: "App Design.pdf",
    type: "pdf",
    size: 8900000,
    modifiedAt: new Date("2024-03-16"),
    createdAt: new Date("2024-03-10"),
    owner: "me",
    parentId: "folder-1",
    path: ["Projects"],
    isFavorite: true,
    isDeleted: false,
  },
  {
    id: "folder-5",
    name: "Client Work",
    type: "folder",
    size: 0,
    modifiedAt: new Date("2024-03-14"),
    createdAt: new Date("2024-02-20"),
    owner: "me",
    parentId: "folder-1",
    path: ["Projects"],
    isFavorite: false,
    isDeleted: false,
  },
  // Files inside Documents folder
  {
    id: "file-6",
    name: "Meeting Notes.document",
    type: "document",
    size: 45000,
    modifiedAt: new Date("2024-03-23"),
    createdAt: new Date("2024-03-23"),
    owner: "me",
    parentId: "folder-2",
    path: ["Documents"],
    isFavorite: false,
    isDeleted: false,
  },
  {
    id: "file-7",
    name: "Contract Draft.pdf",
    type: "pdf",
    size: 1200000,
    modifiedAt: new Date("2024-03-20"),
    createdAt: new Date("2024-03-18"),
    owner: "me",
    parentId: "folder-2",
    path: ["Documents"],
    isFavorite: false,
    isDeleted: false,
  },
  // Files inside Images folder
  {
    id: "file-8",
    name: "Team Photo.jpg",
    type: "image",
    size: 4500000,
    modifiedAt: new Date("2024-03-18"),
    createdAt: new Date("2024-03-18"),
    owner: "me",
    parentId: "folder-3",
    path: ["Images"],
    isFavorite: true,
    isDeleted: false,
  },
  {
    id: "file-9",
    name: "Product Screenshots.zip",
    type: "archive",
    size: 25000000,
    modifiedAt: new Date("2024-03-15"),
    createdAt: new Date("2024-03-15"),
    owner: "me",
    parentId: "folder-3",
    path: ["Images"],
    isFavorite: false,
    isDeleted: false,
  },
  {
    id: "file-10",
    name: "Logo Design.png",
    type: "image",
    size: 850000,
    modifiedAt: new Date("2024-03-12"),
    createdAt: new Date("2024-03-10"),
    owner: "me",
    parentId: "folder-3",
    path: ["Images"],
    isFavorite: false,
    isDeleted: false,
  },
  // Shared files
  {
    id: "file-11",
    name: "Collaboration Doc.document",
    type: "document",
    size: 78000,
    modifiedAt: new Date("2024-03-10"),
    createdAt: new Date("2024-02-28"),
    owner: "John Doe",
    parentId: "folder-4",
    path: ["Shared with me"],
    isFavorite: false,
    isDeleted: false,
  },
  {
    id: "file-12",
    name: "Project Video.mp4",
    type: "video",
    size: 150000000,
    modifiedAt: new Date("2024-03-08"),
    createdAt: new Date("2024-03-01"),
    owner: "Jane Smith",
    parentId: "folder-4",
    path: ["Shared with me"],
    isFavorite: false,
    isDeleted: false,
  },
  // More files for search variety
  {
    id: "file-13",
    name: "Annual Report 2023.pdf",
    type: "pdf",
    size: 4200000,
    modifiedAt: new Date("2024-01-15"),
    createdAt: new Date("2024-01-15"),
    owner: "me",
    parentId: null,
    path: [],
    isFavorite: false,
    isDeleted: false,
  },
  {
    id: "file-14",
    name: "Podcast Episode 1.mp3",
    type: "audio",
    size: 45000000,
    modifiedAt: new Date("2024-02-20"),
    createdAt: new Date("2024-02-20"),
    owner: "me",
    parentId: null,
    path: [],
    isFavorite: false,
    isDeleted: false,
  },
  {
    id: "file-15",
    name: "Analytics Dashboard.pdf",
    type: "pdf",
    size: 1800000,
    modifiedAt: new Date("2024-03-05"),
    createdAt: new Date("2024-03-01"),
    owner: "me",
    parentId: "folder-1",
    path: ["Projects"],
    isFavorite: false,
    isDeleted: false,
  },
  // Deleted files (for Trash)
  {
    id: "file-16",
    name: "Old Draft.document",
    type: "document",
    size: 35000,
    modifiedAt: new Date("2024-02-10"),
    createdAt: new Date("2024-01-20"),
    owner: "me",
    parentId: null,
    path: [],
    isFavorite: false,
    isDeleted: true,
  },
  {
    id: "file-17",
    name: "Unused Image.png",
    type: "image",
    size: 1200000,
    modifiedAt: new Date("2024-02-05"),
    createdAt: new Date("2024-01-15"),
    owner: "me",
    parentId: null,
    path: [],
    isFavorite: false,
    isDeleted: true,
  },
]

export const recentSearches = [
  "Q1 Report",
  "Project presentation",
  "Budget 2024",
  "Team photos",
  "Meeting notes",
]

export const suggestedFiles = mockFiles.slice(0, 4)
